### PR TITLE
Added time calculator idea

### PR DESCRIPTION
**Pull request by thadseaver**
I'm a noob with Github so hopefully I did everything right. Everything seemed to go OK. Please don't hesitate to critique.

Thad

### CODE REVIEW

**Comment by melanierichards** [comment]
Thanks @thadseaver! My only feedback is to change the markdown for the headings so that they match the style here: https://help.github.com/articles/basic-writing-and-formatting-syntax/ (`##` etc only appears before the text, not after). Sorry for not having that in the contribution guidelines, but thanks for helping me to make those better! :P

**Comment by thadseaver** [comment]
@melanierichards Syntax has been fixed. Markdown Pad, my editor, formatted those headings for me. I'll have to keep an eye on that.

No need to apologize.  Thanks for letting me contribute! :)

**Comment by melanierichards** [comment]
Thanks @thadseaver, merged!!

thankyou

FYI, I "squashed" the commits in your pull request when I merged the PR, that basically takes the smaller, more granular commits and creates one complete "idea" commit for the work that you contributed. That will make it a bit easier to review the history of the project. :]

**Comment by thadseaver** [comment]
Alright! :+1:

**Pull request merged**
