### PR TITLE
Add Create a web app that automates a common task

### PR DESCRIPTION
**Pull request by thadseaver**

### CODE REVIEW

**Comment by thadseaver** [comment]
@melanierichards  I don't know how I missed this, but it looks like you've got this idea already. Or at least something very close to it.

"Identify a need you have in your daily life and make a web app that addresses it"

**Comment by melanierichards** [comment]
Yeah, I think I'll close this PR since it's a duplicate. Thanks anyway!

**Comment by thadseaver** [comment]
Would it be cheating if I added a project that I did a few years ago to the _inspired by_ page based on this idea? Actually, I have two. They were both inspired by this idea, though they predate this repo.

**Comment by melanierichards** [comment]
I'd prefer to list only projects inspired by this repo. Now you have to make more things! :P

**Pull request closed without merging**
