### PR TITLE
Add suggestion for recreating your favorite poster

### PR DESCRIPTION
**Pull request by qaid**

### CODE REVIEW

**Comment by melanierichards** [comment]
@qaid this is a fantastic idea! Some updates have been merged into the main repo since you submitted this pull request, would you mind merging those into your fork and pushing up to this PR? Then we'll be all set. Thanks!

**Comment by qaid** [comment]
Ah ok. Cool, no problem. Will do.

**Comment by qaid** [comment]
Whoops. Didn't realize deleting the branch in my repo would trickle up to a deletion of the branch as a pending PR.

I made a separate PR ( #6 ) that is identical, but with the most up to date changes from your master baked in.

Cheers!

**Comment by melanierichards** [comment]
@qaid huh, I didn't know that either! Taking a look now

**Pull request closed without merging**
