### PR TITLE
Time clock

### PR DESCRIPTION
**Pull request by thadseaver**
@melanierichards Added time clock idea.

### CODE REVIEW

**Comment by melanierichards** [comment]
@thadseaver in the details you have that an error should be returned for an action that can't be performed right now (trying to clock out when you're on lunch break, for ex); what do you think about instead having the instructions say to disable actions that are not currently available and display the user's current status?

**Comment by thadseaver** [comment]
@melanierichards The only problem I have with that is the time clock will be used by multiple people (all employees). I envision it to work like our time clock at work. It displays a home screen with all the buttons and a field to enter the employee number. Joe walks in, enters his employee number, then presses clock in. A message that Joe clocked in successfully displays for ~3 seconds, then returns to home screen. A few minutes later, Linda repeats this process. That situation doesn't lend itself very well to having disabled buttons and current status.

However, if the home screen simply asked for the employee number, then upon entering it, only the appropriate buttons are enabled (though all are displayed) and the current status is displayed, **that** would accomplish what you're after.

I'm OK with either option. What do you think?

**Comment by thadseaver** [comment]
@melanierichards Hmm, what about the reports button? Using your recommendation, it would always be enabled, correct?

The system would already know which employee to get report data for since the employee number was already entered. Using my original idea, after clicking reports, the user would then have to be prompted for the employee number. Either way, the employee number has to be entered so whether it's done before or after...it's a wash.

Overall, I like your idea better.

**Comment by melanierichards** [comment]
Hey @thadseaver, sorry it took me so long to get back to you. Folks in town. :]

`However, if the home screen simply asked for the employee number, then upon entering it, only the appropriate buttons are enabled` This is basically what I was envisioning. 

So we can update the guidelines to that if you'd like, or we could have them be more general and it's up to the dev to decide on their interface but suggest that they think about how they'd handle actions that can't currently be taken by a particular employee #.

**Comment by thadseaver** [comment]
@melanierichards See what you think.

**Comment by melanierichards** [comment]
@thadseaver looks good, thanks! If you update your PR with the new commits from the base repo, this'll be ready for me to merge.

**Comment by thadseaver** [comment]
@melanierichards All set!

**Comment by melanierichards** [comment]
Thanks again @thadseaver!

By the way, it looks like you made updates from the main repo manually, so in the future here's some instructions on how to fetch updates/commits from the main repo and merge them into your fork:

https://help.github.com/articles/fork-a-repo/#step-3-configure-git-to-sync-your-fork-with-the-original-spoon-knife-repository (step 3 under "Keep your fork synced")
https://help.github.com/articles/fetching-a-remote/

**Comment by thadseaver** [comment]
@melanierichards Thanks for the links! Yes, I had some troubles updating. Still learning...

**Comment by melanierichards** [comment]
@thadseaver no worries! Git stuff tends to be one of those things where you learn as you need it. There's plenty of things I don't know because they haven't come up in my projects or aren't a part of my teams' workflows.

**Pull request merged**
