### PR TITLE
Add Random number generator for picking lottery numbers

### PR DESCRIPTION
**Pull request by thadseaver**

### CODE REVIEW

**Comment by melanierichards** [comment]
Thanks @thadseaver! One quick update: can you update the list-like content (such as interface elements) so that they are markdown lists (ul)?

Ex:

```
* Thing
* Another thing
```

Also, I merged your other PR so you'll need to update from the master repo.

**Comment by thadseaver** [comment]
> One quick update: can you update the list-like content (such as interface elements) so that they are markdown lists (ul)?

Sure, but I didn't for [Make a Time Calculator](https://github.com/melanierichards/just-build-websites/blob/master/docs/time-calculator.md) and most of [Make a time clock web app](https://github.com/melanierichards/just-build-websites/blob/master/docs/time-clock.md). Should I update those as well?

**Comment by thadseaver** [comment]
@melanierichards I'm lost. My master branch shows that I'm even with your master but my lottery-numbers branch is 2 commits ahead and 2 commits behind your master according to Github. In the command line, both branches say _nothing to commit, working directory clean._ 

I've tried merge and pull from [this page you sent me](https://help.github.com/articles/fetching-a-remote/) but I get a _not something we can merge_ error.

Any advice? In the meantime, I'll keep googling.

**Comment by melanierichards** [comment]
You'd need to do a `git fetch` instead of a `git pull` from the main repo. On your command line do `git remote -v` to double-check you have the right name for the main repo. Let's say it's called "main". You'd then do `git fetch main`, and that will bring down the changes. Then do `git merge main/master` (or it's `git merge main master`, I always forget) to actually merge the changes into your master branch.

**Comment by melanierichards** [comment]
Oh also feel free to update the other ideas to have those bullets as well.

**Comment by thadseaver** [comment]
In the command line, does it matter if I'm on my master or lottery-number branch when I use those commands?

**Comment by melanierichards** [comment]
Oh yeah sorry I guess you'd be pulling into whatever your current branch is (so `lottery-number` in this case)

**Comment by thadseaver** [comment]
@melanierichards Not sure why it worked, but it did.

**Comment by melanierichards** [comment]
Thanks @thadseaver, sorry it took me so long to look at this last update!

**Pull request merged**
